- name: install dependent packages
  apt: name="{{ item }}" update_cache=yes
  with_items:
    - python-pip
    - build-essential
    - python-dev
    - git
    - python-imaging

- name: install pip packages
  pip: name="{{ item }}"
  with_items:
    - tornado

- name: clone the GateOne source
  git: repo="{{ GATEONE_REPO }}" dest=/opt/GateOne
  notify: restart gateone

- name: clone the GateOne config
  git: repo="{{ GATEONE_CONFIG_REPO }}" dest=/opt/gateone-config
  notify: restart gateone

- name: setup install GateOne
  shell: python setup.py install chdir=/opt/GateOne

- name: install the systemd service
  file: src=/opt/GateOne/scripts/init/gateone.service dest=/etc/systemd/system/gateone.service state=link

# commented out for now, but could be useful for generating new certs
#- name: generate the configuration file
#  shell: /usr/local/bin/gateone --configure creates=/etc/gateone/conf.d/10server.conf

- name: ensure conf directory exists
  file: dest=/etc/gateone/conf.d/ state=directory
  with_items:
    - "/etc/gateone/conf.d/"
    - "/etc/gateone/ssl/"

- name: link configuration files for now
  file: src="/opt/gateone-config/{{ item }}" dest="/etc/gateone/conf.d/{{ item }}" state=link
  with_items:
    - 10server.conf
    - 20authentication.conf
    - 50terminal.conf
    - ssh_config_global

- name: link the source ssl files
  file: src="{{SSH_HOST_SRC}}/{{ item }}" dest="/etc/gateone/ssl/{{ item }}" state=link force=yes
  with_items:
    - "{{ SSH_HOST_KEY }}"
    - "{{ SSH_HOST_CERT }}"
  notify: restart gateone

- name: enable the gateone service
  service: name=gateone enabled=yes state=started
  notify: restart gateone

###
# This section is to define firewall rules
###

- include: ufw.yml
  when: UFW_DO_CONFIGURE
