###
# This section is to define firewall rules
###

- name: enable ufw
  ufw: state=enabled policy=reject logging=off

- name: enable incoming
  ufw: rule=allow src="{{ item.ip }}" port="{{ item.port }}"
  with_items:
    UFW_INCOMING_ALLOW

- name: enable outgoing rules
  ufw: rule=allow direction=out to_ip=any to_port=67

- name: enable outgoing rules
  ufw: rule=allow direction=out dest="{{ item.ip }}" port="{{ item.port }}"
  with_items:
    UFW_OUTGOING_ALLOW

- name: disable outgoing default
  ufw: policy=reject direction=outgoing
